---
- hosts: blog_node
  become: true
  vars:
    web_root: /var/www/myblog
  tasks:
    - name: Install mysql db
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - mysql56-server
        - mysql56-devel
        - httpd
    - name: Get wordpress package
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip
    - unarchive:
        src: /tmp/wordpress.zip
        dest: /var/www
        remote_src: True
    - command: mv /var/www/wordpress "{{ web_root }}"
    - template:
        src: templates/blog_vhost.conf
        dest: /etc/httpd/conf.d/blog.conf
    - service:
        name: httpd
        state: restarted
    - name: Remove welcome conf
      file:
        path: /etc/httpd/conf.d/welcome.conf
        state: absent
